import { z } from 'zod'
import { anthropic, ANTHROPIC_MODELS } from '@/lib/anthropic/client'
import type { ReportData } from './data'

/**
 * The prose sections of a client report. Generated by Claude (Stage 3) and
 * validated against this schema; the PDF (Stage 2) renders from it. Defined here
 * so both stages share one contract.
 */
export const NarrativeSchema = z.object({
  executive_summary: z.string(),
  highlights: z.array(z.string()),
  work_completed: z.array(
    z.object({
      section_title: z.string(),
      items: z.array(z.string()),
    })
  ),
  hours_commentary: z.string(),
  next_period: z.array(z.string()),
  risks_or_blockers: z.array(z.string()),
})

export type Narrative = z.infer<typeof NarrativeSchema>

/** An empty narrative — used to render a data-only PDF before the LLM runs. */
export const EMPTY_NARRATIVE: Narrative = {
  executive_summary: '',
  highlights: [],
  work_completed: [],
  hours_commentary: '',
  next_period: [],
  risks_or_blockers: [],
}

const SYSTEM_PROMPT = `You are writing the prose sections of a professional weekly/monthly consulting status report for a client.

Audience: end client decision-maker. Probably not technical. Wants to know value delivered.

Rules:
- Lead with outcomes, not activities. "Confirmed two pilot firms" not "Held three calls."
- No filler ("synergy", "leverage", "robust", "journey", "exciting"). No corporate empty calories.
- Use commas, full stops, parentheses, colons. Never em dashes.
- Specific over vague. Quantify where possible.
- Past tense for completed work, future tense for next period.
- 2-3 sentence executive summary at the top, written as the consultant signing off.
- Group work by theme, not by day or by task. "Distributor outreach" with the specific things done.
- Hours commentary: factual, no padding. "32 of 40 retainer hours used. 8 in reserve for completion-stage work."
- Don't fabricate. If a task description is vague, summarise faithfully rather than embellish.
- Don't include risks or blockers unless they're real. Empty array is fine.

Return strict JSON matching this schema, and nothing else:
{
  "executive_summary": string,
  "highlights": string[],
  "work_completed": [{ "section_title": string, "items": string[] }],
  "hours_commentary": string,
  "next_period": string[],
  "risks_or_blockers": string[]
}`

/** Compact, grounded representation of the data for the model. */
function buildPayload(data: ReportData) {
  const retainer =
    data.engagement.included_hours != null
      ? { included_hours: data.engagement.included_hours, used_hours: data.hours_summary.total, used_pct: data.totals.vs_retainer_pct }
      : null
  return {
    engagement: data.engagement.name,
    client: data.engagement.end_client,
    period: { from: data.period.start, to: data.period.end },
    hours: { total: data.hours_summary.total, billable: data.hours_summary.billable, retainer },
    completed_tasks: data.tasks_completed.map((t) => ({ title: t.title, detail: t.description, project: t.project_name })),
    time_log: data.time_entries.map((e) => ({ date: e.work_date, hours: e.hours, project: e.project?.name ?? null, task: e.engagement_task?.title ?? null, notes: e.notes })),
    by_project: data.hours_summary.by_project,
  }
}

async function callClaude(data: ReportData, extra: string): Promise<string> {
  const response = await anthropic.messages.create({
    model: ANTHROPIC_MODELS.SONNET,
    max_tokens: 2000,
    system: (SYSTEM_PROMPT + extra).trim(),
    messages: [{ role: 'user', content: JSON.stringify(buildPayload(data)) }],
  })
  const block = response.content.find((b) => b.type === 'text')
  return block && block.type === 'text' ? block.text : ''
}

function parseNarrative(text: string): Narrative | null {
  const clean = text
    .replace(/^```json\n?/i, '')
    .replace(/^```\n?/, '')
    .replace(/\n?```$/, '')
    .trim()
  try {
    const result = NarrativeSchema.safeParse(JSON.parse(clean))
    return result.success ? result.data : null
  } catch {
    return null
  }
}

/**
 * Draft the report narrative with Claude. Validates against NarrativeSchema; on
 * a parse/validation miss, retries once with a stricter instruction, then throws.
 * If the engagement has no retainer, the model is told to omit retainer language.
 */
export async function generateNarrative(
  data: ReportData,
  opts: { tone?: 'consulting' | 'agency' } = {}
): Promise<Narrative> {
  const toneNote = opts.tone === 'agency' ? '\n\nTone: friendly and warm, but still concise.' : ''
  const retainerNote =
    data.engagement.included_hours == null
      ? '\n\nThis engagement has no retainer. Do NOT mention retainer hours, caps, or reserves in hours_commentary; just state hours worked.'
      : ''

  const first = parseNarrative(await callClaude(data, toneNote + retainerNote))
  if (first) return first

  const stricter =
    '\n\nYour previous response was not valid JSON for the schema. Return ONLY a single JSON object matching the schema exactly. No prose, no markdown fences, no commentary.'
  const second = parseNarrative(await callClaude(data, toneNote + retainerNote + stricter))
  if (second) return second

  throw new Error('Could not generate a valid report narrative. Try again, or write it manually.')
}
