import { z } from 'zod'

/**
 * The prose sections of a client report. Generated by Claude (Stage 3) and
 * validated against this schema; the PDF (Stage 2) renders from it. Defined here
 * so both stages share one contract.
 */
export const NarrativeSchema = z.object({
  executive_summary: z.string(),
  highlights: z.array(z.string()),
  work_completed: z.array(
    z.object({
      section_title: z.string(),
      items: z.array(z.string()),
    })
  ),
  hours_commentary: z.string(),
  next_period: z.array(z.string()),
  risks_or_blockers: z.array(z.string()),
})

export type Narrative = z.infer<typeof NarrativeSchema>

/** An empty narrative — used to render a data-only PDF before the LLM runs. */
export const EMPTY_NARRATIVE: Narrative = {
  executive_summary: '',
  highlights: [],
  work_completed: [],
  hours_commentary: '',
  next_period: [],
  risks_or_blockers: [],
}
